version: '3.0'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  api:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongodb